# Process GREIN Rat Data

Retrieve the downloaded expression data, update gene identifiers to entrez, and curate sample IDs. The script will also identify a balanced hold-out test set to compare projection performance into learned latent spaces across algorithms.

In [7]:
import os
import random
import pandas as pd
from sklearn.model_selection import train_test_split

In [8]:
random.seed(1234)

## Read Phenotype Information: skipping until phenotype data found

In [9]:
# path = os.path.join('download', 'TARGET_phenotype.gz')
# pheno_df = pd.read_table(path)

# print(pheno_df.shape)
# pheno_df.head(3)

## Read Probe Mapping Info 
(where chromosomes start and end, saved in a file in downloads)

In [10]:
# path = os.path.join('download', 'gencode.v23.annotation.gene.probemap')
# probe_map_df = pd.read_table(path)

# # Inner merge gene df to get ensembl to entrez mapping
# probe_map_df = probe_map_df.merge(gene_df, how='inner', left_on='gene', right_on='symbol')

# # Mapping to rename gene expression index
# ensembl_to_entrez = dict(zip(probe_map_df.id, probe_map_df.entrez_gene_id))

# print(probe_map_df.shape)
# probe_map_df.head(3)

## Read Gene Expression Data

In [15]:
# reading in rat gene expression data

file = "/work/pi_hrando_smith_edu/biobombe/BioBombe/0.expression-download/download/grein_count_matrix_rat.pkl"
expr_df = pd.read_pickle(file)

print(expr_df.shape)
expr_df.head(4)

(18171, 3756)

                 gene gene_symbol  GSM2668015  GSM2668016  GSM2668017  \
0  ENSRNOG00000000007        Gad1   5140.2551   2873.5173   3494.3567
1  ENSRNOG00000000008        Alx4     88.3117     54.3955     68.8133
2  ENSRNOG00000000009      Tmco5b     71.9091     47.7813     50.4332
3  ENSRNOG00000000010       Cbln1    366.8392    236.4766    388.1470

   GSM2668018  GSM2668019  GSM2668020  GSM2668021  GSM2668022  GSM2674552  \
0   2488.5614   2180.0086   4054.4603   3249.2422   2984.1460         0.0
1     54.5058     61.3839     84.8890     92.7423     62.1657         0.0
2     41.1147     40.6470     56.4535     48.4759     47.5353         0.0
3    212.8647    218.2449    392.4068    325.6375    231.4440         0.0

   GSM2674553  GSM2674554  GSM2674555  GSM2674556  GSM2674557  GSM2674558  \
0         0.0         0.0         0.0         0.0         0.0      0.0000
1         0.0         0.0         2.0         0.0         2.0      1.2676
2         0.0         0.0         0.0         0.0         0.0      0.0000
3         0.0         0.0         0.0         0.0         0.0      0.0000

   GSM2674559  GSM2674560  GSM2674561  GSM2674562  GSM2674563  GSM2674564  \
0         0.0         0.0         0.0         0.0         0.0      0.0000
1         1.0         0.0         1.0         0.0         2.0      1.0000
2         0.0         0.0         0.0         0.0         0.0      0.9999
3         0.0         0.0         0.0         0.0         0.0      0.0000

   GSM2674565  GSM2674566  GSM2674567  GSM2683306  GSM2683307  GSM2683308  \
0         0.0         0.0         0.0     52.5118     27.5834     70.6123
1         0.0         0.0         2.0    101.9639     77.8544     77.2475
2         0.0         0.0         0.0     76.9727     42.2429     54.0743
3         0.0         0.0         0.0    126.6326     97.5128     89.0460

   GSM2683309  GSM2683310  GSM2683311  GSM2683312  GSM2699989  GSM2699990  \
0     55.3001     60.6636     64.8627      0.0000      0.0000      0.0000
1     67.0283     61.0076     92.9832     75.9176     10.0072     10.2904
2     83.0249     56.5682     75.6148     44.3473      0.0000      0.0000
3    141.5510    100.1295    143.5802     87.1007     80.7889     95.8700

   GSM2699991  GSM2699992  GSM2699993  GSM2699994  GSM2715971  GSM2715972  \
0      0.0000      0.0000      0.0000      0.0000   8077.0649   9227.4000
1     12.9965      5.2917      2.9983      2.9982      7.7212      3.2585
2      1.9925      0.0000      0.0000      0.0000      2.0026      3.0024
3     88.7592      0.0000      0.9978      0.0000    191.7057     95.8997

   GSM2715973  GSM2715974  GSM2715975  GSM2715976  GSM2715977  GSM2715978  \
0   7751.7759  11005.4183   7258.2656   7750.9521   7443.6661   5799.0544
1      4.6087     11.5565      2.1514      9.2553     12.8524      2.2403
2      1.0007      7.0039      0.0000      2.0028      6.0125      3.0032
3    489.5682    179.7031     46.8661    538.9243    185.3860     31.9538

   GSM2715979  GSM2715980  GSM2715981  GSM2715982  GSM2715983  GSM2715984  \
0   3756.6748   9460.1003   8944.9772   7345.0705   2688.1169   1287.2608
1      8.8704      7.9846      8.7620      9.1957      6.6126      2.2129
2      1.0013      7.0090      7.0133      0.0000      0.9997      0.0000
3    154.6727    380.6273     68.8234    542.4091     91.0773     15.0045

   GSM2715985  GSM2715986  GSM2715987  GSM2715988  GSM2715989  GSM2715990  \
0   2727.9509   3056.5858   2186.0269   1057.4510   2667.3995   2199.3065
1      4.1951      5.4406      4.3549      4.3307      1.0794      0.0000
2      1.9966      1.9996      0.9989      0.0000      0.9994      0.0000
3     59.0517    109.9586     22.0312     39.0011     93.9846     20.0015

   GSM2715991  GSM2715992  GSM2715993  GSM2715994  GSM2715995  GSM2715996  \
0   4680.5883   2260.7557   5828.5459   2227.6616   3363.4133    992.8633
1      6.2299      2.2114      1.1305      3.2939      1.0986      1.2788
2      0.9984      1.9978      3.9983      0.0000      4.9929      0.9985
3    214.1116     26.0145     76.9255    161.9481    115.0825     10.0015

   GSM2715997  GSM2715998  GSM2715999  GSM2716000  GSM2716001  GSM2716002  \
0   1842.5045   1404.8854   2517.8330   3006.0525   3477.9592   2256.6627
1      2.1894      0.0000      4.3445      4.4178      4.7062     11.0629
2      0.0000      1.9976      2.9939      0.9994      3.9929      3.0002
3     46.0030     55.0061     14.0206    196.0334     91.0751     15.9833

   GSM2716003  GSM2716004  GSM2716005  GSM2716006  GSM2716007  GSM2716008  \
0   1586.4363   2187.9468   2674.1143   2016.9581   2742.1812   2547.0596
1      3.7057      5.7963      6.1173      2.3366     12.6389      2.3165
2      1.9959      1.9999      1.9998      2.9974      1.9986      0.9982
3     51.0427     21.9955     52.9815     79.9588    123.0765     40.0105

   GSM2716009  GSM2716010  GSM2716011  GSM2716012  GSM2716013  GSM2716014  \
0   2457.7646   2654.3481   2474.3228   2446.7151   3479.4022   2363.2974
1      6.2326      8.9240      2.2051      1.1714      3.5922      5.5352
2      0.0000      3.9984      0.9992      2.9980      2.9956      1.9986
3     77.0529    152.0539     33.0284     55.9996     64.0337     17.9933

   GSM2716015  GSM2716016  GSM2716017  GSM2716018  GSM2716019  GSM2716020  \
0   2130.8833   2153.1366   1885.0844   1609.9812   2604.1562   2357.5022
1      2.1364      2.2271      3.3355      3.6840      1.1024      5.5521
2      0.9982      0.9997      1.9985      0.9992      0.9989      0.0000
3    137.1276     31.9856     30.9817    125.0081     62.0252     23.0186

   GSM2716021  GSM2716022  GSM2716023  GSM2716024  GSM2716025  GSM2716026  \
0   1631.9068   3623.0229   2368.8172   3113.3028   6896.8506   7489.0872
1      1.1313      2.2729      1.0971      5.7430      9.9963      6.7728
2      0.9982      1.9978      1.9961      0.9980     10.0095      3.0060
3     81.0676    118.1329     53.0852    149.0673     34.9733     42.9355

   GSM2716027  GSM2716028  GSM2716029  GSM2716030  GSM2716031  GSM2716032  \
0   7412.5133   4597.7440   4899.0524   6031.4952   5026.4837   7712.4545
1     16.8338      7.7801      6.6201      5.4313      7.8609      3.3459
2      2.0015      5.0060      3.9985      3.0053      4.0068      6.0056
3    326.9224    228.6216    126.2238     88.9173     81.8720    168.1948

   GSM2716033  GSM2716034  GSM2716035  GSM2716036  GSM2716037  GSM2716038  \
0   7431.7311   2848.8045   1570.6430   2385.4432   3116.3150   2394.2515
1     10.7153      4.5273      1.1105      6.2747      9.1597     19.1858
2      3.0027      5.0049      1.0024      4.0029      5.0000      0.0000
3    240.9992     56.9776    404.0848     74.9642     79.0182    425.0618

   GSM2716039  GSM2716040  GSM2716041  GSM2716042  GSM2716043  GSM2716044  \
0   2513.2903   1470.2933   2111.4910   1861.1502   1559.5226   2142.7398
1      4.4250      4.2916      3.1714      5.5165      1.1489      0.0000
2      0.0000      1.9975      0.9995      1.0002      2.0027      1.0007
3     80.8868     31.0276     64.0309    349.0578     21.9854    155.9389

   GSM2716045  GSM2716046  GSM2716047  GSM2716048  GSM2716049  GSM2716050  \
0   1591.1334   1969.2836   1369.3257   2925.1458   1347.1719   2125.1370
1      3.5640      7.3520      3.3687      6.3815      8.8651      3.5560
2      0.0000      2.0032      0.0000      0.9996      0.0000      0.0000
3     59.9721     22.9600     51.0562    109.9542    237.8447    327.8264

   GSM2716051  GSM2716052  GSM2716053  GSM2716054  GSM2716055  GSM2716056  \
0    943.7186   2098.6572   1451.7287   2926.1412   1625.0765   1868.2216
1      1.0989      2.2454      1.0329      2.2616      2.1099      0.0000
2      0.0000      2.0005      1.0003      4.0044      0.0000      1.0009
3     40.9633     51.9942    141.0610     42.9804     96.9721    314.8716

   GSM2716057  GSM2716058  GSM2716059  GSM2716060  GSM2716061  GSM2716062  \
0   1994.7574   2378.0431    408.6917   2637.7173   1901.5484   1981.6590
1      0.0000      6.3931      2.3200      7.5756      3.3233     55.0980
2      0.0000      1.9995      0.0000      0.9999      0.0000      1.0002
3     62.9657     88.0778     15.0294    100.9399    189.9120     47.0185

   GSM2716063  GSM2716064  GSM2716065  GSM2716066  GSM2716067  GSM2716068  \
0   2323.8591   1595.1175   2444.7900   2115.6710   2367.9683   1914.8664
1      4.6347      6.7324      3.2574      1.0712      2.4069      4.3683
2      2.0001      1.0010      2.0027      0.0000      4.0041      0.0000
3     72.0371     84.9352     26.9680     62.9166     28.9779     31.9472

   GSM2716069  GSM2716070  GSM2716071  GSM2716072  GSM2750963  GSM2750964  \
0   2294.9325   2015.1430   2686.5707   3444.9325      0.0000      0.0000
1      4.6107      4.7192      3.2074      3.4956      0.0000      0.0000
2      3.0050      2.9964      1.9986      0.9983      0.9984      0.0000
3     76.8661     81.1519     68.1035     52.1197    795.7104    813.4364

   GSM2750965  GSM2750966  GSM2750967  GSM2750968  GSM2752505  GSM2752506  \
0      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000
1      0.0000      2.2362      1.1368      0.0000      4.3549      5.6932
2      0.0000      0.0000      0.0000      0.0000      4.1480      1.0846
3    920.4176    659.0641    756.8048    885.1883      6.8414      3.5776

   GSM2778522  GSM2778523  GSM2778524  GSM2778525  GSM2778526  GSM2778527  \
0      0.0000       0.000         0.0         0.0         0.0         0.0
1      4.7644       6.165         0.0         0.0         0.0         0.0
2      5.0593       0.000         0.0         0.0         0.0         0.0
3      0.0000       0.000         0.0         0.0         0.0         0.0

   GSM2778528  GSM2778529  GSM2778530  GSM2778531  GSM2778532  GSM2778533  \
0         0.0         0.0      0.0000      0.0000         0.0         0.0
1         0.0         0.0      0.9992      4.3526         0.0         0.0
2         0.0         0.0      0.0000      0.0000         0.0         0.0
3         0.0         0.0      0.0000      0.0000         0.0         0.0

   GSM2778534  GSM2778535  GSM2778536  GSM2778537  GSM2778538  GSM2778539  \
0         0.0         0.0         0.0         0.0         0.0         0.0
1         0.0         0.0         0.0         0.0         0.0         0.0
2         0.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         0.0         0.0         0.0

   GSM2778540  GSM2778541  GSM2778542  GSM2778543  GSM2778544  GSM2778545  \
0         0.0         0.0         0.0      0.0000      0.0000         0.0
1         0.0         0.0         0.0      1.0002      1.0006         0.0
2         0.0         0.0         0.0      0.0000      0.0000         0.0
3         0.0         0.0         0.0      0.0000      0.0000         0.0

   GSM2778546  GSM2778547  GSM2778548  GSM2778549  GSM2778550  GSM2778551  \
0         0.0         0.0       0.000         0.0         0.0         0.0
1         0.0         0.0       0.988         0.0         0.0         0.0
2         0.0         0.0       0.000         0.0         0.0         0.0
3         0.0         0.0       0.000         0.0         0.0         0.0

   GSM2778552  GSM2778553  GSM2778554  GSM2778555  GSM2778556  GSM2778557  \
0      0.0000         0.0         0.0         0.0         0.0         0.0
1      0.6472         0.0         0.0         0.0         0.0         0.0
2      0.0000         0.0         0.0         0.0         0.0         0.0
3      0.0000         0.0         0.0         0.0         0.0         0.0

   GSM2778558  GSM2778559  GSM2778560  GSM2778561  GSM2778562  GSM2778563  \
0         0.0         0.0         0.0         0.0         0.0         0.0
1         0.0         0.0         0.0         0.0         0.0         0.0
2         0.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         0.0         0.0         0.0

   GSM2778564  GSM2778565  GSM2778566  GSM2778567  GSM2778568  GSM2778569  \
0         0.0         0.0         0.0         0.0         0.0         0.0
1         0.0         0.0         0.0         0.0         0.0         0.0
2         0.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         0.0         0.0         0.0

   GSM2778570  GSM2778571  GSM2778572  GSM2778573  GSM2778574  GSM2778575  \
0         0.0         0.0         0.0         0.0         0.0         0.0
1         0.0         0.0         0.0         0.0         0.0         0.0
2         0.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         0.0         0.0         0.0

   GSM2778576  GSM2778577  GSM2778578  GSM2778579  GSM2778580  GSM2778581  \
0         0.0         0.0      0.0000         0.0         0.0         0.0
1         0.0         0.0      1.0021         0.0         0.0         0.0
2         0.0         0.0      0.0000         0.0         0.0         0.0
3         0.0         0.0      0.0000         0.0         0.0         0.0

   GSM2778582  GSM2778583  GSM2778584  GSM2778585  GSM2778586  GSM2778587  \
0         0.0      0.0000      0.0000       0.000      0.0000         0.0
1         0.0      1.0139      1.0254       2.001      1.0002         0.0
2         0.0      0.0000      0.0000       0.000      0.0000         0.0
3         0.0      0.0000      0.0000       0.000      0.0000         0.0

   GSM2778588  GSM2778589  GSM2778590  GSM2778591  GSM2778592  GSM2778593  \
0         0.0         0.0         0.0         0.0      0.0000         0.0
1         0.0         0.0         0.0         0.0      0.3322         0.0
2         0.0         0.0         0.0         0.0      0.0000         0.0
3         0.0         0.0         0.0         0.0      0.0000         0.0

   GSM2778594  GSM2778595  GSM2778596  GSM2778597  GSM2778598  GSM2778599  \
0         0.0      0.0000         0.0         0.0         0.0      0.0000
1         0.0      1.6866         0.0         0.0         0.0      2.0007
2         0.0      0.0000         0.0         0.0         0.0      0.0000
3         0.0      0.0000         0.0         0.0         0.0      0.0000

   GSM2778600  GSM2778601  GSM2778602  GSM2778603  GSM2778604  GSM2778605  \
0         0.0         0.0         0.0         0.0         0.0         0.0
1         0.0         0.0         0.0         0.0         0.0         0.0
2         0.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         0.0         0.0         0.0

   GSM2778606  GSM2778607  GSM2778608  GSM2778609  GSM2778610  GSM2778611  \
0         0.0         0.0      0.0000         0.0         0.0         0.0
1         0.0         0.0    111.4827         0.0         0.0         0.0
2         0.0         0.0      0.0000         0.0         0.0         0.0
3         0.0         0.0      0.0000         0.0         0.0         0.0

   GSM2778612  GSM2778613  GSM2778614  GSM2778615  GSM2778616  GSM2778617  \
0         0.0         0.0         0.0         0.0         0.0         0.0
1         0.0         0.0         0.0         0.0         0.0         0.0
2         0.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         0.0         0.0         0.0

   GSM2778618  GSM2778619  GSM2778620  GSM2778621  GSM2778622  GSM2778623  \
0         0.0         0.0         0.0         0.0         0.0         0.0
1         0.0         0.0         0.0         0.0         0.0         0.0
2         0.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         0.0         0.0         0.0

   GSM2778624  GSM2778625  GSM2778626  GSM2778627  GSM2778628  GSM2778629  \
0         0.0         0.0         0.0         0.0         0.0         0.0
1         0.0         0.0         0.0         0.0         0.0         0.0
2         0.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         0.0         0.0         0.0

   GSM2778630  GSM2778631  GSM2778632  GSM2778633  GSM2778634  GSM2778635  \
0         0.0         0.0         0.0         0.0         0.0         0.0
1         0.0         0.0         0.0         0.0         0.0         0.0
2         0.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         0.0         0.0         0.0

   GSM2778636  GSM2778637  GSM2778638  GSM2752528  GSM2752529  GSM2752530  \
0         0.0         0.0         0.0         0.0         0.0      0.0000
1         0.0         0.0         0.0         0.0         0.0      3.0101
2         0.0         0.0         0.0         0.0         0.0      0.0000
3         0.0         0.0         0.0         0.0         0.0      0.0000

   GSM2752531  GSM2752532  GSM2752533  GSM2753240  GSM2753241  GSM2753242  \
0         0.0      0.0000      0.0000      0.0000      0.0000      0.0000
1         0.0      2.3952      2.9517     88.0929     38.1826     52.9904
2         0.0      0.0000      0.0000     19.0431      8.0000     14.1639
3         0.0      0.0000      0.0000     57.1060     25.0487     31.0749

   GSM2753243  GSM2753244  GSM2753245  GSM2753246  GSM2753247  GSM2753248  \
0      0.0000      0.0000      0.0000      0.0000     37.5772      0.0000
1     72.5944     36.8151     80.2023     62.5704     82.0871     61.3772
2     11.1599     23.0000     17.7130     13.1052     34.4969     28.6241
3     30.7616     33.9136    167.7782     79.5829     48.4803     77.7011

   GSM2756537  GSM2756538  GSM2777235  GSM2777236  GSM2777237  GSM2777238  \
0     13.7458     39.9932     19.5937      0.0000      9.2461      0.0000
1    286.2268    296.5489      0.0000     11.9542      0.0000      3.1953
2    130.8852    111.2355      4.9994      0.9999     14.9998      3.9997
3    219.9800    250.9703      5.0057      0.0000      2.0020     30.0017

   GSM2777239  GSM2777240  GSM2777241  GSM2777242  GSM2777243  GSM2777244  \
0      0.0000     21.6149      9.0435      0.0000      0.0000      0.0000
1      7.5374      9.4343     11.0021      2.1410      1.3348      1.1027
2     19.0009     26.9836     11.0034      0.0000      3.0003      8.0082
3      0.0000      7.0070      0.0000      2.0053      2.9990      2.9962

   GSM2777245  GSM2777246  GSM2777247  GSM2777248  GSM2777249  GSM2777250  \
0      0.0000      0.0000      0.0000      0.0000     11.6119      0.0000
1      9.1248     35.3561      9.2323      2.4313      1.0335      3.3607
2      4.0022      0.0000      0.0000     23.9977      1.0002      5.9994
3      2.9964      0.9992      1.9988      0.0000     19.0209      0.0000

   GSM2777251  GSM2777252  GSM2777253  GSM2777254  GSM2836818  GSM2836819  \
0      5.3071      0.0000      7.3670      0.0000      0.0000      1.3276
1      7.2067      9.8155      0.0000     21.8174      1.9968      0.9976
2      8.0036      0.0000     39.9942      0.0000      0.9985      0.0000
3      0.0000      0.9991      0.0000      4.9866      0.0000      0.0000

   GSM2836820  GSM2836821  GSM2836822  GSM2836823  GSM2836824  GSM2836825  \
0      0.0000       0.000      0.0000         0.0      0.0000      0.0000
1      0.0000       0.996      1.9956         0.0      1.9936      1.9986
2      0.9993       1.994      0.0000         0.0      0.9976      1.9985
3      0.0000       0.000      0.0000         0.0      1.9913      0.0000

   GSM2836826  GSM2836827  GSM2836828  GSM2836829  GSM2836830  GSM2836831  \
0      0.0000      0.0000      0.0000      0.0000         0.0      0.0000
1      0.9988      0.0000      0.0000      0.9939         0.0      0.0000
2      0.0000      0.9975      1.9941      0.0000         0.0      1.0023
3      0.0000      0.0000      0.0000      0.0000         0.0      0.0000

   GSM2836832  GSM2836833  GSM2836834  GSM2836835  GSM2836836  GSM2836837  \
0      0.0000      0.0000         0.0      0.0000      0.0000         0.0

In [16]:
# Clean up x and y from expr_df

# create a list of cleaned columns
cleaned_column = ['gene', 'gene_symbol']
for column in expr_df.drop(['gene', 'gene_symbol'], axis = 1).columns:
    cleaned_column.append(column.split("_")[0])

# set colums to cleaned column
expr_df.columns = cleaned_column

In [17]:
# Check that it worked

pd.set_option('display.max_columns', None) 
expr_df.head()

                 gene gene_symbol  GSM2668015  GSM2668016  GSM2668017  \
0  ENSRNOG00000000007        Gad1   5140.2551   2873.5173   3494.3567
1  ENSRNOG00000000008        Alx4     88.3117     54.3955     68.8133
2  ENSRNOG00000000009      Tmco5b     71.9091     47.7813     50.4332
3  ENSRNOG00000000010       Cbln1    366.8392    236.4766    388.1470
4  ENSRNOG00000000012       Tcf15    164.0565     86.1982     86.2113

   GSM2668018  GSM2668019  GSM2668020  GSM2668021  GSM2668022  GSM2674552  \
0   2488.5614   2180.0086   4054.4603   3249.2422   2984.1460         0.0
1     54.5058     61.3839     84.8890     92.7423     62.1657         0.0
2     41.1147     40.6470     56.4535     48.4759     47.5353         0.0
3    212.8647    218.2449    392.4068    325.6375    231.4440         0.0
4     86.0566    100.7740    145.9362     98.5538     97.6332         0.0

   GSM2674553  GSM2674554  GSM2674555  GSM2674556  GSM2674557  GSM2674558  \
0      0.0000         0.0      0.0000         0.0         0.0      0.0000
1      0.0000         0.0      2.0000         0.0         2.0      1.2676
2      0.0000         0.0      0.0000         0.0         0.0      0.0000
3      0.0000         0.0      0.0000         0.0         0.0      0.0000
4      1.7998         0.0      1.4823         0.0         0.0      0.0000

   GSM2674559  GSM2674560  GSM2674561  GSM2674562  GSM2674563  GSM2674564  \
0         0.0         0.0         0.0         0.0         0.0      0.0000
1         1.0         0.0         1.0         0.0         2.0      1.0000
2         0.0         0.0         0.0         0.0         0.0      0.9999
3         0.0         0.0         0.0         0.0         0.0      0.0000
4         0.0         0.0         0.0         0.0         0.0      0.0000

   GSM2674565  GSM2674566  GSM2674567  GSM2683306  GSM2683307  GSM2683308  \
0      0.0000         0.0         0.0     52.5118     27.5834     70.6123
1      0.0000         0.0         2.0    101.9639     77.8544     77.2475
2      0.0000         0.0         0.0     76.9727     42.2429     54.0743
3      0.0000         0.0         0.0    126.6326     97.5128     89.0460
4      2.4423         0.0         0.0     31.8007     33.2070     33.8593

   GSM2683309  GSM2683310  GSM2683311  GSM2683312  GSM2699989  GSM2699990  \
0     55.3001     60.6636     64.8627      0.0000      0.0000      0.0000
1     67.0283     61.0076     92.9832     75.9176     10.0072     10.2904
2     83.0249     56.5682     75.6148     44.3473      0.0000      0.0000
3    141.5510    100.1295    143.5802     87.1007     80.7889     95.8700
4     47.3560     26.0843     30.6765     43.2454      9.9237     13.7869

   GSM2699991  GSM2699992  GSM2699993  GSM2699994  GSM2715971  GSM2715972  \
0      0.0000      0.0000      0.0000      0.0000   8077.0649   9227.4000
1     12.9965      5.2917      2.9983      2.9982      7.7212      3.2585
2      1.9925      0.0000      0.0000      0.0000      2.0026      3.0024
3     88.7592      0.0000      0.9978      0.0000    191.7057     95.8997
4      6.8718      3.3902      5.8108     10.7463    102.1026    223.3905

   GSM2715973  GSM2715974  GSM2715975  GSM2715976  GSM2715977  GSM2715978  \
0   7751.7759  11005.4183   7258.2656   7750.9521   7443.6661   5799.0544
1      4.6087     11.5565      2.1514      9.2553     12.8524      2.2403
2      1.0007      7.0039      0.0000      2.0028      6.0125      3.0032
3    489.5682    179.7031     46.8661    538.9243    185.3860     31.9538
4    169.2790    144.5358    179.2563    174.8670    184.6195    136.6068

   GSM2715979  GSM2715980  GSM2715981  GSM2715982  GSM2715983  GSM2715984  \
0   3756.6748   9460.1003   8944.9772   7345.0705   2688.1169   1287.2608
1      8.8704      7.9846      8.7620      9.1957      6.6126      2.2129
2      1.0013      7.0090      7.0133      0.0000      0.9997      0.0000
3    154.6727    380.6273     68.8234    542.4091     91.0773     15.0045
4    189.9708    167.3157    221.3517    170.9751     36.2959     28.0860

   GSM2715985  GSM2715986  GSM2715987  GSM2715988  GSM2715989  GSM2715990  \
0   2727.9509   3056.5858   2186.0269   1057.4510   2667.3995   2199.3065
1      4.1951      5.4406      4.3549      4.3307      1.0794      0.0000
2      1.9966      1.9996      0.9989      0.0000      0.9994      0.0000
3     59.0517    109.9586     22.0312     39.0011     93.9846     20.0015
4     52.0860     44.0378     52.0537     37.7665     21.7810     39.7728

   GSM2715991  GSM2715992  GSM2715993  GSM2715994  GSM2715995  GSM2715996  \
0   4680.5883   2260.7557   5828.5459   2227.6616   3363.4133    992.8633
1      6.2299      2.2114      1.1305      3.2939      1.0986      1.2788
2      0.9984      1.9978      3.9983      0.0000      4.9929      0.9985
3    214.1116     26.0145     76.9255    161.9481    115.0825     10.0015
4     83.7334     35.5279    110.8544     34.1406     46.1739     22.4126

   GSM2715997  GSM2715998  GSM2715999  GSM2716000  GSM2716001  GSM2716002  \
0   1842.5045   1404.8854   2517.8330   3006.0525   3477.9592   2256.6627
1      2.1894      0.0000      4.3445      4.4178      4.7062     11.0629
2      0.0000      1.9976      2.9939      0.9994      3.9929      3.0002
3     46.0030     55.0061     14.0206    196.0334     91.0751     15.9833
4     35.1244     21.9305     71.0108     53.9407     60.8413     45.9540

   GSM2716003  GSM2716004  GSM2716005  GSM2716006  GSM2716007  GSM2716008  \
0   1586.4363   2187.9468   2674.1143   2016.9581   2742.1812   2547.0596
1      3.7057      5.7963      6.1173      2.3366     12.6389      2.3165
2      1.9959      1.9999      1.9998      2.9974      1.9986      0.9982
3     51.0427     21.9955     52.9815     79.9588    123.0765     40.0105
4     65.1429     25.1598     40.3402     34.5369     36.2361     41.1544

   GSM2716009  GSM2716010  GSM2716011  GSM2716012  GSM2716013  GSM2716014  \
0   2457.7646   2654.3481   2474.3228   2446.7151   3479.4022   2363.2974
1      6.2326      8.9240      2.2051      1.1714      3.5922      5.5352
2      0.0000      3.9984      0.9992      2.9980      2.9956      1.9986
3     77.0529    152.0539     33.0284     55.9996     64.0337     17.9933
4     41.9273     33.7298     50.6996     38.5862     39.0497     62.2687

   GSM2716015  GSM2716016  GSM2716017  GSM2716018  GSM2716019  GSM2716020  \
0   2130.8833   2153.1366   1885.0844   1609.9812   2604.1562   2357.5022
1      2.1364      2.2271      3.3355      3.6840      1.1024      5.5521
2      0.9982      0.9997      1.9985      0.9992      0.9989      0.0000
3    137.1276     31.9856     30.9817    125.0081     62.0252     23.0186
4     55.5534     38.7630     51.3647     39.0476     39.9764     47.6479

   GSM2716021  GSM2716022  GSM2716023  GSM2716024  GSM2716025  GSM2716026  \
0   1631.9068   3623.0229   2368.8172   3113.3028   6896.8506   7489.0872
1      1.1313      2.2729      1.0971      5.7430      9.9963      6.7728
2      0.9982      1.9978      1.9961      0.9980     10.0095      3.0060
3     81.0676    118.1329     53.0852    149.0673     34.9733     42.9355
4     38.2864     49.7786     53.9873     62.4591    186.1930    182.3535

   GSM2716027  GSM2716028  GSM2716029  GSM2716030  GSM2716031  GSM2716032  \
0   7412.5133   4597.7440   4899.0524   6031.4952   5026.4837   7712.4545
1     16.8338      7.7801      6.6201      5.4313      7.8609      3.3459
2      2.0015      5.0060      3.9985      3.0053      4.0068      6.0056
3    326.9224    228.6216    126.2238     88.9173     81.8720    168.1948
4    248.0010    179.0028    143.4444    212.1188    137.6599    192.7812

   GSM2716033  GSM2716034  GSM2716035  GSM2716036  GSM2716037  GSM2716038  \
0   7431.7311   2848.8045   1570.6430   2385.4432   3116.3150   2394.2515
1     10.7153      4.5273      1.1105      6.2747      9.1597     19.1858
2      3.0027      5.0049      1.0024      4.0029      5.0000      0.0000
3    240.9992     56.9776    404.0848     74.9642     79.0182    425.0618
4    266.0925     70.1436     15.6578     42.8326     34.7113     39.2133

   GSM2716039  GSM2716040  GSM2716041  GSM2716042  GSM2716043  GSM2716044  \
0   2513.2903   1470.2933   2111.4910   1861.1502   1559.5226   2142.7398
1      4.4250      4.2916      3.1714      5.5165      1.1489      0.0000
2      0.0000      1.9975      0.9995      1.0002      2.0027      1.0007
3     80.8868     31.0276     64.0309    349.0578     21.9854    155.9389
4     62.0538     20.5881     29.4026     28.0549     23.7634     36.6249

   GSM2716045  GSM2716046  GSM2716047  GSM2716048  GSM2716049  GSM2716050  \
0   1591.1334   1969.2836   1369.3257   2925.1458   1347.1719   2125.1370
1      3.5640      7.3520      3.3687      6.3815      8.8651      3.5560
2      0.0000      2.0032      0.0000      0.9996      0.0000      0.0000
3     59.9721     22.9600     51.0562    109.9542    237.8447    327.8264
4     41.4586     23.8409     17.4570     69.6719     13.0192     38.7307

   GSM2716051  GSM2716052  GSM2716053  GSM2716054  GSM2716055  GSM2716056  \
0    943.7186   2098.6572   1451.7287   2926.1412   1625.0765   1868.2216
1      1.0989      2.2454      1.0329      2.2616      2.1099      0.0000
2      0.0000      2.0005      1.0003      4.0044      0.0000      1.0009
3     40.9633     51.9942    141.0610     42.9804     96.9721    314.8716
4     24.8029     51.1265     32.2733     45.4346     33.2392     28.1416

   GSM2716057  GSM2716058  GSM2716059  GSM2716060  GSM2716061  GSM2716062  \
0   1994.7574   2378.0431    408.6917   2637.7173   1901.5484   1981.6590
1      0.0000      6.3931      2.3200      7.5756      3.3233     55.0980
2      0.0000      1.9995      0.0000      0.9999      0.0000      1.0002
3     62.9657     88.0778     15.0294    100.9399    189.9120     47.0185
4     49.8846     29.7788     32.3494     61.0112     20.3574     33.8501

   GSM2716063  GSM2716064  GSM2716065  GSM2716066  GSM2716067  GSM2716068  \
0   2323.8591   1595.1175   2444.7900   2115.6710   2367.9683   1914.8664
1      4.6347      6.7324      3.2574      1.0712      2.4069      4.3683
2      2.0001      1.0010      2.0027      0.0000      4.0041      0.0000
3     72.0371     84.9352     26.9680     62.9166     28.9779     31.9472
4     52.7710     22.7746     31.4067     56.4984     37.4873     31.2387

   GSM2716069  GSM2716070  GSM2716071  GSM2716072  GSM2750963  GSM2750964  \
0   2294.9325   2015.1430   2686.5707   3444.9325      0.0000      0.0000
1      4.6107      4.7192      3.2074      3.4956      0.0000      0.0000
2      3.0050      2.9964      1.9986      0.9983      0.9984      0.0000
3     76.8661     81.1519     68.1035     52.1197    795.7104    813.4364
4     75.5515     44.3210     52.9799     41.2889     10.9451      6.8123

   GSM2750965  GSM2750966  GSM2750967  GSM2750968  GSM2752505  GSM2752506  \
0      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000
1      0.0000      2.2362      1.1368      0.0000      4.3549      5.6932
2      0.0000      0.0000      0.0000      0.0000      4.1480      1.0846
3    920.4176    659.0641    756.8048    885.1883      6.8414      3.5776
4     10.4080     16.0549     24.3121     23.1445     72.2245     93.4262

   GSM2778522  GSM2778523  GSM2778524  GSM2778525  GSM2778526  GSM2778527  \
0      0.0000      0.0000      0.0000        0.00         0.0      0.0000
1      4.7644      6.1650      0.0000        0.00         0.0      0.0000
2      5.0593      0.0000      0.0000        0.00         0.0      0.0000
3      0.0000      0.0000      0.0000        0.00         0.0      0.0000
4     33.8489     11.1108     46.0013        0.35         0.0      1.0047

   GSM2778528  GSM2778529  GSM2778530  GSM2778531  GSM2778532  GSM2778533  \
0      0.0000         0.0      0.0000      0.0000      0.0000         0.0
1      0.0000         0.0      0.9992      4.3526      0.0000         0.0
2      0.0000         0.0      0.0000      0.0000      0.0000         0.0
3      0.0000         0.0      0.0000      0.0000      0.0000         0.0
4    149.1076         0.0     23.4843     18.1462     68.8693         0.0

   GSM2778534  GSM2778535  GSM2778536  GSM2778537  GSM2778538  GSM2778539  \
0         0.0      0.0000         0.0      0.0000      0.0000         0.0
1         0.0      0.0000         0.0      0.0000      0.0000         0.0
2         0.0      0.0000         0.0      0.0000      0.0000         0.0
3         0.0      0.0000         0.0      0.0000      0.0000         0.0
4         0.0      6.9203         0.0      1.1938     76.2397         0.0

   GSM2778540  GSM2778541  GSM2778542  GSM2778543  GSM2778544  GSM2778545  \
0         0.0      0.0000         0.0      0.0000      0.0000         0.0
1         0.0      0.0000         0.0      1.0002      1.0006         0.0
2         0.0      0.0000         0.0      0.0000      0.0000         0.0
3         0.0      0.0000         0.0      0.0000      0.0000         0.0
4         0.0      3.0042         0.0      0.0000      0.0000         0.0

   GSM2778546  GSM2778547  GSM2778548  GSM2778549  GSM2778550  GSM2778551  \
0         0.0         0.0       0.000         0.0         0.0         0.0
1         0.0         0.0       0.988         0.0         0.0         0.0
2         0.0         0.0       0.000         0.0         0.0         0.0
3         0.0         0.0       0.000         0.0         0.0         0.0
4         0.0         0.0       0.000         0.0         0.0         0.0

   GSM2778552  GSM2778553  GSM2778554  GSM2778555  GSM2778556  GSM2778557  \
0      0.0000         0.0      0.0000      0.0000      0.0000         0.0
1      0.6472         0.0      0.0000      0.0000      0.0000         0.0
2      0.0000         0.0      0.0000      0.0000      0.0000         0.0
3      0.0000         0.0      0.0000      0.0000      0.0000         0.0
4      0.0000         0.0     15.8739    182.1673      0.9869         0.0

   GSM2778558  GSM2778559  GSM2778560  GSM2778561  GSM2778562  GSM2778563  \
0         0.0         0.0         0.0      0.0000         0.0         0.0
1         0.0         0.0         0.0      0.0000         0.0         0.0
2         0.0         0.0         0.0      0.0000         0.0         0.0
3         0.0         0.0         0.0      0.0000         0.0         0.0
4         0.0         0.0         0.0     68.3837         0.0         0.0

   GSM2778564  GSM2778565  GSM2778566  GSM2778567  GSM2778568  GSM2778569  \
0         0.0         0.0         0.0      0.0000      0.0000         0.0
1         0.0         0.0         0.0      0.0000      0.0000         0.0
2         0.0         0.0         0.0      0.0000      0.0000         0.0
3         0.0         0.0         0.0      0.0000      0.0000         0.0
4         0.0         0.0         0.0      3.3161      3.1647         0.0

   GSM2778570  GSM2778571  GSM2778572  GSM2778573  GSM2778574  GSM2778575  \
0         0.0      0.0000         0.0      0.0000         0.0         0.0
1         0.0      0.0000         0.0      0.0000         0.0         0.0
2         0.0      0.0000         0.0      0.0000         0.0         0.0
3         0.0      0.0000         0.0      0.0000         0.0         0.0
4         0.0      2.8945         0.0      7.4169         0.0         0.0

   GSM2778576  GSM2778577  GSM2778578  GSM2778579  GSM2778580  GSM2778581  \
0         0.0         0.0      0.0000      0.0000      0.0000      0.0000
1         0.0         0.0      1.0021      0.0000      0.0000      0.0000
2         0.0         0.0      0.0000      0.0000      0.0000      0.0000
3         0.0         0.0      0.0000      0.0000      0.0000      0.0000
4         0.0         0.0      0.0000      4.0601      4.6061      0.9645

   GSM2778582  GSM2778583  GSM2778584  GSM2778585  GSM2778586  GSM2778587  \
0         0.0      0.0000      0.0000      0.0000      0.0000         0.0
1         0.0      1.0139      1.0254      2.0010      1.0002         0.0
2         0.0      0.0000      0.0000      0.0000      0.0000         0.0
3         0.0      0.0000      0.0000      0.0000      0.0000         0.0
4         0.0      0.0000      0.0000      3.0034      0.0653         0.0

   GSM2778588  GSM2778589  GSM2778590  GSM2778591  GSM2778592  GSM2778593  \
0         0.0         0.0         0.0      0.0000      0.0000         0.0
1         0.0         0.0         0.0      0.0000      0.3322         0.0
2         0.0         0.0         0.0      0.0000      0.0000         0.0
3         0.0         0.0         0.0      0.0000      0.0000         0.0
4         0.0         0.0         0.0      1.5019      7.1377         0.0

   GSM2778594  GSM2778595  GSM2778596  GSM2778597  GSM2778598  GSM2778599  \
0         0.0      0.0000      0.0000      0.0000         0.0      0.0000
1         0.0      1.6866      0.0000      0.0000         0.0      2.0007
2         0.0      0.0000      0.0000      0.0000         0.0      0.0000
3         0.0      0.0000      0.0000      0.0000         0.0      0.0000
4         0.0      0.0000      4.4904      1.0172         0.0     17.9440

   GSM2778600  GSM2778601  GSM2778602  GSM2778603  GSM2778604  GSM2778605  \
0         0.0      0.0000       0.000      0.0000      0.0000      0.0000
1         0.0      0.0000       0.000      0.0000      0.0000      0.0000
2         0.0      0.0000       0.000      0.0000      0.0000      0.0000
3         0.0      0.0000       0.000      0.0000      0.0000      0.0000
4         0.0      8.8624      11.311      3.1826      9.1901      5.9242

   GSM2778606  GSM2778607  GSM2778608  GSM2778609  GSM2778610  GSM2778611  \
0         0.0      0.0000      0.0000      0.0000         0.0      0.0000
1         0.0      0.0000    111.4827      0.0000         0.0      0.0000
2         0.0      0.0000      0.0000      0.0000         0.0      0.0000
3         0.0      0.0000      0.0000      0.0000         0.0      0.0000
4         0.0      1.4856      0.0000      0.2828         0.0      1.8916

   GSM2778612  GSM2778613  GSM2778614  GSM2778615  GSM2778616  GSM2778617  \
0         0.0      0.0000      0.0000         0.0         0.0         0.0
1         0.0      0.0000      0.0000         0.0         0.0         0.0
2         0.0      0.0000      0.0000         0.0         0.0         0.0
3         0.0      0.0000      0.0000         0.0         0.0         0.0
4         0.0      5.4489      7.9113         0.0         0.0         0.0

   GSM2778618  GSM2778619  GSM2778620  GSM2778621  GSM2778622  GSM2778623  \
0       0.000         0.0         0.0      0.0000      0.0000         0.0
1       0.000         0.0         0.0      0.0000      0.0000         0.0
2       0.000         0.0         0.0      0.0000      0.0000         0.0
3       0.000         0.0         0.0      0.0000      0.0000         0.0
4      25.142         0.0         0.0      6.3301      2.1501         0.0

   GSM2778624  GSM2778625  GSM2778626  GSM2778627  GSM2778628  GSM2778629  \
0         0.0      0.0000      0.0000         0.0         0.0         0.0
1         0.0      0.0000      0.0000         0.0         0.0         0.0
2         0.0      0.0000      0.0000         0.0         0.0         0.0
3         0.0      0.0000      0.0000         0.0         0.0         0.0
4         0.0     14.7612      1.1279         0.0         0.0         0.0

   GSM2778630  GSM2778631  GSM2778632  GSM2778633  GSM2778634  GSM2778635  \
0      0.0000         0.0         0.0      0.0000         0.0         0.0
1      0.0000         0.0         0.0      0.0000         0.0         0.0
2      0.0000         0.0         0.0      0.0000         0.0         0.0
3      0.0000         0.0         0.0      0.0000         0.0         0.0
4      2.4072         0.0         0.0     14.1387         0.0         0.0

   GSM2778636  GSM2778637  GSM2778638  GSM2752528  GSM2752529  GSM2752530  \
0         0.0         0.0         0.0      0.0000      0.0000      0.0000
1         0.0         0.0         0.0      0.0000      0.0000      3.0101
2         0.0         0.0         0.0      0.0000      0.0000      0.0000

## Process gene expression matrix

This involves updating Entrez gene ids, sorting and subsetting

In [18]:
# expr_df = (expr_df
#     .dropna(axis='rows')
#     .reindex(probe_map_df.id)
#     .rename(index=ensembl_to_entrez)
#     .rename(index=old_to_new_entrez)
#     .groupby(level=0).mean()
#     .transpose()
#     .sort_index(axis='rows')
#     .sort_index(axis='columns')
# )

expr_df.index.rename('sample_id', inplace=True)

print(expr_df.shape)
expr_df.head(2)

(18171, 3756)

,gene,gene_symbol,GSM2668015,GSM2668016,GSM2668017,GSM2668018,GSM2668019,GSM2668020,GSM2668021,GSM2668022,GSM2674552,GSM2674553,GSM2674554,GSM2674555,GSM2674556,GSM2674557,GSM2674558,GSM2674559,GSM2674560,GSM2674561,GSM2674562,GSM2674563,GSM2674564,GSM2674565,GSM2674566,GSM2674567,GSM2683306,GSM2683307,GSM2683308,GSM2683309,GSM2683310,GSM2683311,GSM2683312,GSM2699989,GSM2699990,GSM2699991,GSM2699992,GSM2699993,GSM2699994,GSM2715971,GSM2715972,GSM2715973,GSM2715974,GSM2715975,GSM2715976,GSM2715977,GSM2715978,GSM2715979,GSM2715980,GSM2715981,GSM2715982,GSM2715983,GSM2715984,GSM2715985,GSM2715986,GSM2715987,GSM2715988,GSM2715989,GSM2715990,GSM2715991,GSM2715992,GSM2715993,GSM2715994,GSM2715995,GSM2715996,GSM2715997,GSM2715998,GSM2715999,GSM2716000,GSM2716001,GSM2716002,GSM2716003,GSM2716004,GSM2716005,GSM2716006,GSM2716007,GSM2716008,GSM2716009,GSM2716010,GSM2716011,GSM2716012,GSM2716013,GSM2716014,GSM2716015,GSM2716016,GSM2716017,GSM2716018,GSM2716019,GSM2716020,GSM2716021,GSM2716022,GSM2716023,GSM2716024,GSM2716025,GSM2716026,GSM2716027,GSM2716028,GSM2716029,GSM2716030,GSM2716031,GSM2716032,GSM2716033,GSM2716034,GSM2716035,GSM2716036,GSM2716037,GSM2716038,GSM2716039,GSM2716040,GSM2716041,GSM2716042,GSM2716043,GSM2716044,GSM2716045,GSM2716046,GSM2716047,GSM2716048,GSM2716049,GSM2716050,GSM2716051,GSM2716052,GSM2716053,GSM2716054,GSM2716055,GSM2716056,GSM2716057,GSM2716058,GSM2716059,GSM2716060,GSM2716061,GSM2716062,GSM2716063,GSM2716064,GSM2716065,GSM2716066,GSM2716067,GSM2716068,GSM2716069,GSM2716070,GSM2716071,GSM2716072,GSM2750963,GSM2750964,GSM2750965,GSM2750966,GSM2750967,GSM2750968,GSM2752505,GSM2752506,GSM2778522,GSM2778523,GSM2778524,GSM2778525,GSM2778526,GSM2778527,GSM2778528,GSM2778529,GSM2778530,GSM2778531,GSM2778532,GSM2778533,GSM2778534,GSM2778535,GSM2778536,GSM2778537,GSM2778538,GSM2778539,GSM2778540,GSM2778541,GSM2778542,GSM2778543,GSM2778544,GSM2778545,GSM2778546,GSM2778547,GSM2778548,GSM2778549,GSM2778550,GSM2778551,GSM2778552,GSM2778553,GSM2778554,GSM2778555,GSM2778556,GSM2778557,GSM2778558,GSM2778559,GSM2778560,GSM2778561,GSM2778562,GSM2778563,GSM2778564,GSM2778565,GSM2778566,GSM2778567,GSM2778568,GSM2778569,GSM2778570,GSM2778571,GSM2778572,GSM2778573,GSM2778574,GSM2778575,GSM2778576,GSM2778577,GSM2778578,GSM2778579,GSM2778580,GSM2778581,GSM2778582,GSM2778583,GSM2778584,GSM2778585,GSM2778586,GSM2778587,GSM2778588,GSM2778589,GSM2778590,GSM2778591,GSM2778592,GSM2778593,GSM2778594,GSM2778595,GSM2778596,GSM2778597,GSM2778598,GSM2778599,GSM2778600,GSM2778601,GSM2778602,GSM2778603,GSM2778604,GSM2778605,GSM2778606,GSM2778607,GSM2778608,GSM2778609,GSM2778610,GSM2778611,GSM2778612,GSM2778613,GSM2778614,GSM2778615,GSM2778616,GSM2778617,GSM2778618,GSM2778619,GSM2778620,GSM2778621,GSM2778622,GSM2778623,GSM2778624,GSM2778625,GSM2778626,GSM2778627,GSM2778628,GSM2778629,GSM2778630,GSM2778631,GSM2778632,GSM2778633,GSM2778634,GSM2778635,GSM2778636,GSM2778637,GSM2778638,GSM2752528,GSM2752529,GSM2752530,GSM2752531,GSM2752532,GSM2752533,GSM2753240,GSM2753241,GSM2753242,GSM2753243,GSM2753244,GSM2753245,GSM2753246,GSM2753247,GSM2753248,GSM2756537,GSM2756538,GSM2777235,GSM2777236,GSM2777237,GSM2777238,GSM2777239,GSM2777240,GSM2777241,GSM2777242,GSM2777243,GSM2777244,GSM2777245,GSM2777246,GSM2777247,GSM2777248,GSM2777249,GSM2777250,GSM2777251,GSM2777252,GSM2777253,GSM2777254,GSM2836818,GSM2836819,GSM2836820,GSM2836821,GSM2836822,GSM2836823,GSM2836824,GSM2836825,GSM2836826,GSM2836827,GSM2836828,GSM2836829,GSM2836830,GSM2836831,GSM2836832,GSM2836833,GSM2836834,GSM2836835,GSM2836836,GSM2836837,GSM2836838,GSM2864807,GSM2864808,GSM2864809,GSM2864810,GSM2864811,GSM2864812,GSM2864813,GSM2864814,GSM2864815,GSM2864816,GSM2864817,GSM2864818,GSM2864819,GSM2864820,GSM2864821,GSM2864822,GSM2864823,GSM2864824,GSM2864825,GSM2864826,GSM2864827,GSM2864828,GSM2864829,GSM2864830,GSM2871682,GSM2871683,GSM2871684,GSM2871685,GSM2871686,GSM2871687,GSM2913798,GSM2913799,GSM2913800,GSM2913801,GSM2913802,GSM2913803,GSM2913804,GSM2913805,GSM2913806,GSM2913807,GSM2913808,GSM2913809,GSM2913810,GSM2913811,GSM2913812,GSM2913813,GSM2913814,GSM2913815,GSM2913816,GSM2913817,GSM2913818,GSM2913819,GSM2913820,GSM2913821,GSM2913822,GSM2913823,GSM2913824,GSM2913825,GSM2913826,GSM2913827,GSM2913828,GSM2913829,GSM2913830,GSM2913831,GSM2913832,GSM2913833,GSM2943055,GSM2943056,GSM2943057,GSM2943058,GSM2943059,GSM2943060,GSM2943061,GSM2943062,GSM2943063,GSM2943064,GSM2943065,GSM2943066,GSM3123061,GSM3123062,GSM3123063,GSM3123064,GSM3123065,GSM3123066,GSM3145829,GSM3145830,GSM3145831,GSM3145832,GSM3145833,GSM3145834,GSM3145835,GSM3145836,GSM3520780,GSM3520781,GSM3520782,GSM3520783,GSM3520784,GSM3520785,GSM3520786,GSM3520787,GSM3520788,GSM3520789,GSM3520790,GSM3520791,GSM3520792,GSM3520793,GSM3520794,GSM3520795,GSM3520796,GSM3520797,GSM3520798,GSM3520799,GSM3520800,GSM3520801,GSM3520802,GSM3520803,GSM3520804,GSM3520805,GSM3520806,GSM3520807,GSM3520808,GSM3520809,GSM3554441,GSM3554442,GSM3554443,GSM3554444,GSM3554445,GSM3554446,GSM3554447,GSM3554448,GSM3554449,GSM3554451,GSM3554453,GSM3554454,GSM3554457,GSM3554459,GSM3554461,GSM3554463,GSM3554465,GSM3554467,GSM3554469,GSM3554471,GSM3554473,GSM3554475,GSM3554477,GSM3554479,GSM3554482,GSM3554485,GSM3554487,GSM3554489,GSM3554493,GSM3554495,GSM3554497,GSM3554499,GSM3554501,GSM3554503,GSM3554505,GSM3554507,GSM3554509,GSM3588967,GSM3588968,GSM3588969,GSM3588970,GSM3588971,GSM3588972,GSM3712411,GSM3712412,GSM3712413,GSM3712414,GSM3712415,GSM3712416,GSM3712417,GSM3712418,GSM4067233,GSM4067234,GSM4067235,GSM4067236,GSM4067237,GSM4067238,GSM4067239,GSM4067240,GSM4067241,GSM4067242,GSM4067243,GSM4067244,GSM4067245,GSM4067246,GSM4067247,GSM4067248,GSM4067249,GSM4067250,GSM4067251,GSM4067252,GSM4067253,GSM4067254,GSM4067255,GSM4067256,GSM4067257,GSM4067258,GSM4067259,GSM4067260,GSM4067261,GSM4067262,GSM4067263,GSM4067264,GSM4067265,GSM4067266,GSM4067267,GSM4067268,GSM4174985,GSM4174986,GSM4174987,GSM4174988,GSM4174989,GSM4174990,GSM4174991,GSM4174992,GSM4174993,GSM4174994,GSM4174995,GSM4174996,GSM4174997,GSM4174998,GSM4174999,GSM4175000,GSM4175001,GSM4175002,GSM4416454,GSM4416455,GSM4416456,GSM4416457,GSM4648537,GSM4648538,GSM4648539,GSM4648540,GSM4648541,GSM4648542,GSM4648543,GSM4648544,GSM4648545,GSM4928727,GSM4928728,GSM4928729,GSM4928730,GSM4928731,GSM4928732,GSM4928733,GSM4928734,GSM4928735,GSM4928736,GSM539553,GSM539554,GSM539555,GSM539556,GSM539557,GSM539558,GSM539559,GSM539560,GSM539561,GSM539562,GSM539563,GSM539564,GSM539565,GSM539566,GSM539567,GSM539568,GSM539569,GSM539570,GSM539571,GSM539572,GSM539573,GSM539574,GSM539575,GSM539576,GSM530339,GSM530340,GSM530341,GSM530342,GSM530343,GSM530344,GSM530345,GSM530346,GSM614808,GSM614809,GSM846150,GSM846151,GSM846152,GSM846153,GSM846154,GSM846155,GSM846156,GSM846157,GSM846158,GSM933100,GSM933101,GSM1039505,GSM1039506,GSM1039507,GSM1039508,GSM1039509,GSM1039510,GSM1039511,GSM1039512,GSM1039513,GSM1077482,GSM1077483,GSM1077484,GSM1077485,GSM1077486,GSM1077487,GSM1079731,GSM1079732,GSM1084028,GSM1084029,GSM1084030,GSM1084031,GSM1084032,GSM1084033,GSM1084034,GSM1084035,GSM1084036,GSM1084037,GSM1084038,GSM1084039,GSM1122813,GSM1122814,GSM1122815,GSM1122816,GSM1122817,GSM1122818,GSM1122819,GSM1122820,GSM1122821,GSM1122822,GSM1122823,GSM1122824,GSM1122825,GSM1122826,GSM1124036,GSM1124037,GSM1124038,GSM1124039,GSM1124040,GSM1124041,GSM1124042,GSM1124043,GSM1133704,GSM1133705,GSM1133706,GSM1133707,GSM1133708,GSM1133709,GSM1133710,GSM1133711,GSM1133712,GSM1133713,GSM1133714,GSM1133715,GSM1150714,GSM1150715,GSM1150716,GSM1150717,GSM1150718,GSM1150719,GSM1150720,GSM1150721,GSM1150722,GSM1150723,GSM1150724,GSM1150725,GSM1150726,GSM1150727,GSM1150728,GSM1150729,GSM1150730,GSM1150731,GSM1150732,GSM1150733,GSM1150734,GSM1150735,GSM1150736,GSM1150737,GSM1150738,GSM1150739,GSM1150740,GSM1150741,GSM1150742,GSM1150743,GSM1150744,GSM1150745,GSM1150746,GSM1150747,GSM1150748,GSM1150749,GSM1150750,GSM1150751,GSM1150752,GSM1150753,GSM1150754,GSM1150755,GSM1150756,GSM1150757,GSM1150758,GSM1150759,GSM1150760,GSM1150761,GSM1150762,GSM1150763,GSM1150764,GSM1150765,GSM1150766,GSM1150767,GSM1150768,GSM1150769,GSM1150770,GSM1150771,GSM1150772,GSM1150773,GSM1150774,GSM1150775,GSM1150776,GSM1150777,GSM1150778,GSM1150779,GSM1150780,GSM1150781,GSM1150782,GSM1150783,GSM1150784,GSM1150785,GSM1150786,GSM1150787,GSM1150788,GSM1150789,GSM1150790,GSM1150791,GSM1150792,GSM1150793,GSM1150794,GSM1150795,GSM1150796,GSM1150797,GSM1150798,GSM1150799,GSM1150800,GSM1150801,GSM1150802,GSM1150803,GSM1150804,GSM1150805,GSM1150806,GSM1150807,GSM1150808,GSM1150809,GSM1150810,GSM1150811,GSM1150812,GSM1150813,GSM1150814,GSM1150815,GSM1150816,GSM1150817,GSM1150818,GSM1150819,GSM1150820,GSM1150821,GSM1150822,GSM1150823,GSM1150824,GSM1150825,GSM1150826,GSM1150827,GSM1150828,GSM1150829,GSM1150830,GSM1150831,GSM1150832,GSM1150833,GSM1150834,GSM1150835,GSM1150836,GSM1150837,GSM1150838,GSM1150839,GSM1150840,GSM1150841,GSM1150842,GSM1150843,GSM1150844,GSM1150845,GSM1150846,GSM1150847,GSM1150848,GSM1150849,GSM1150850,GSM1150851,GSM1150852,GSM1150853,GSM1150854,GSM1150855,GSM1150856,GSM1150857,GSM1173208,GSM1173209,GSM1174814,GSM1174815,GSM1174816,GSM1174817,GSM1174818,GSM1174819,GSM1174820,GSM1174821,GSM1198709,GSM1198710,GSM1207184,GSM1207185,GSM1207186,GSM1207187,GSM1207188,GSM1207189,GSM1207190,GSM1207191,GSM1207192,GSM1207193,GSM1207194,GSM1212702,GSM1212703,GSM1212704,GSM1212705,GSM1212706,GSM1212707,GSM1212708,GSM1212709,GSM1212710,GSM1212711,GSM1212712,GSM1212713,GSM1212714,GSM1212715,GSM1212716,GSM1212717,GSM1212718,GSM1212719,GSM1212720,GSM1212721,GSM1212722,GSM1212723,GSM1212724,GSM1212725,GSM1212726,GSM1212727,GSM1212728,GSM1212729,GSM1212730,GSM1212731,GSM1212732,GSM1212733,GSM1212734,GSM1212735,GSM1212736,GSM1212737,GSM1212738,GSM1212739,GSM1212740,GSM1212741,GSM1212742,GSM1212743,GSM1212744,GSM1212745,GSM1212746,GSM1212747,GSM1212748,GSM1212749,GSM1213660,GSM1213661,GSM1213662,GSM1213663,GSM1213664,GSM1213665,GSM1213666,GSM1213667,GSM1213668,GSM1219036,GSM1219037,GSM1219038,GSM1219039,GSM1219040,GSM1219041,GSM1219042,GSM1219043,GSM1219044,GSM1219045,GSM1219046,GSM1219047,GSM1219048,GSM1219049,GSM1219050,GSM1219051,GSM1300229,GSM1300230,GSM1300231,GSM1300232,GSM1300233,GSM1300234,GSM1300235,GSM1300236,GSM1300237,GSM1300238,GSM1300239,GSM1300240,GSM1300241,GSM1300242,GSM1300243,GSM1300244,GSM1300245,GSM1300246,GSM1302237,GSM1302238,GSM1302239,GSM1302240,GSM1302241,GSM1302242,GSM1302243,GSM1302244,GSM1302245,GSM1302246,GSM1302247,GSM1302248,GSM1302249,GSM1302250,GSM1302251,GSM1302252,GSM1302253,GSM1302254,GSM1302255,GSM1302256,GSM1302257,GSM1302258,GSM1302259,GSM1302260,GSM1302261,GSM1302262,GSM1302263,GSM1302264,GSM1302265,GSM1302266,GSM1302267,GSM1302268,GSM1302269,GSM1302270,GSM1302271,GSM1302272,GSM1302273,GSM1328469,GSM1328470,GSM1328471,GSM1328472,GSM1328473,GSM1328474,GSM1328475,GSM1328476,GSM1328477,GSM1328478,GSM1328479,GSM1328480,GSM1328481,GSM1328482,GSM1328483,GSM1328484,GSM1328485,GSM1328486,GSM1328487,GSM1328488,GSM1328489,GSM1328490,GSM1328491,GSM1328492,GSM1328493,GSM1328494,GSM1328495,GSM1328496,GSM1328497,GSM1328498,GSM1328499,GSM1328500,GSM1328501,GSM1328502,GSM1328503,GSM1328504,GSM1328505,GSM1328506,GSM1328507,GSM1328508,GSM1328509,GSM1328510,GSM1328511,GSM1328512,GSM1328513,GSM1328514,GSM1328515,GSM1328516,GSM1328517,GSM1328518,GSM1328519,GSM1328520,GSM1328521,GSM1328522,GSM1328523,GSM1328524,GSM1328525,GSM1328526,GSM1328527,GSM1328528,GSM1328529,GSM1328530,GSM1328531,GSM1328532,GSM1328533,GSM1328534,GSM1328535,GSM1328536,GSM1328537,GSM1328538,GSM1328539,GSM1328540,GSM1328541,GSM1328542,GSM1328543,GSM1328544,GSM1328545,GSM1328546,GSM1328547,GSM1328548,GSM1328549,GSM1328550,GSM1328551,GSM1328552,GSM1328553,GSM1328554,GSM1328555,GSM1328556,GSM1328557,GSM1328558,GSM1328559,GSM1328560,GSM1328561,GSM1328562,GSM1328563,GSM1328564,GSM1328565,GSM1328566,GSM1328567,GSM1328568,GSM1328569,GSM1328570,GSM1328571,GSM1328572,GSM1328573,GSM1328574,GSM1328575,GSM1328576,GSM1328577,GSM1328578,GSM1328579,GSM1328580,GSM1328581,GSM1328582,GSM1328583,GSM1328584,GSM1328585,GSM1328586,GSM1328587,GSM1328588,GSM1328589,GSM1328590,GSM1328591,GSM1328592,GSM1328593,GSM1328594,GSM1328595,GSM1328596,GSM1328597,GSM1328598,GSM1328599,GSM1328600,GSM1328601,GSM1328602,GSM1328603,GSM1328604,GSM1328605,GSM1328606,GSM1328607,GSM1328608,GSM1328609,GSM1328610,GSM1328611,GSM1328612,GSM1328613,GSM1328614,GSM1328615,GSM1328616,GSM1328617,GSM1328618,GSM1328619,GSM1328620,GSM1328621,GSM1328622,GSM1328623,GSM1328624,GSM1328625,GSM1328626,GSM1328627,GSM1328628,GSM1328629,GSM1328630,GSM1328631,GSM1328632,GSM1328633,GSM1328634,GSM1328635,GSM1328636,GSM1328637,GSM1328638,GSM1328639,GSM1328640,GSM1328641,GSM1328642,GSM1328643,GSM1328644,GSM1328645,GSM1328646,GSM1328647,GSM1328648,GSM1328649,GSM1328650,GSM1328651,GSM1328652,GSM1328653,GSM1328654,GSM1328655,GSM1328656,GSM1328657,GSM1328658,GSM1328659,GSM1328660,GSM1328661,GSM1328662,GSM1328663,GSM1328664,GSM1328665,GSM1328666,GSM1328667,GSM1328668,GSM1328669,GSM1328670,GSM1328671,GSM1328672,GSM1328673,GSM1328674,GSM1328675,GSM1328676,GSM1328677,GSM1328678,GSM1328679,GSM1328680,GSM1328681,GSM1328682,GSM1328683,GSM1328684,GSM1328685,GSM1328686,GSM1328687,GSM1328688,GSM1328689,GSM1328690,GSM1328691,GSM1328692,GSM1328693,GSM1328694,GSM1328695,GSM1328696,GSM1328697,GSM1328698,GSM1328699,GSM1328700,GSM1328701,GSM1328702,GSM1328703,GSM1328704,GSM1328705,GSM1328706,GSM1328707,GSM1328708,GSM1328709,GSM1328710,GSM1328711,GSM1328712,GSM1328713,GSM1328714,GSM1328715,GSM1328716,GSM1328717,GSM1328718,GSM1328719,GSM1328720,GSM1328721,GSM1328722,GSM1328723,GSM1328724,GSM1328725,GSM1328726,GSM1328727,GSM1328728,GSM1328729,GSM1328730,GSM1328731,GSM1328732,GSM1328733,GSM1328734,GSM1328735,GSM1328736,GSM1328737,GSM1328738,GSM1328739,GSM1328740,GSM1328741,GSM1328742,GSM1328743,GSM1328744,GSM1328745,GSM1328746,GSM1328747,GSM1328748,GSM1328749,GSM1328750,GSM1328751,GSM1328752,GSM1328753,GSM1328754,GSM1328755,GSM1328756,GSM1328757,GSM1328758,GSM1328759,GSM1328760,GSM1328761,GSM1328762,GSM1328763,GSM1328764,GSM1328765,GSM1328766,GSM1328767,GSM1328768,GSM1328769,GSM1328770,GSM1328771,GSM1328772,GSM1328773,GSM1328774,GSM1328775,GSM1328776,GSM1328777,GSM1328778,GSM1328779,GSM1328780,GSM1328781,GSM1328782,GSM1328783,GSM1328784,GSM1328785,GSM1328786,GSM1328787,GSM1328788,GSM1308536,GSM1308537,GSM1308538,GSM1308539,GSM1308540,GSM1308541,GSM1308542,GSM1308543,GSM1321560,GSM1321561,GSM1321562,GSM1321563,GSM1321564,GSM1321565,GSM1321566,GSM1321567,GSM1321568,GSM1321569,GSM1321570,GSM1321571,GSM1357492,GSM1357493,GSM1357494,GSM1357495,GSM1357496,GSM1357497,GSM1357498,GSM1357499,GSM1357500,GSM1357501,GSM1357502,GSM1357503,GSM1357504,GSM1367790,GSM1367791,GSM1367792,GSM1367793,GSM1367794,GSM1367795,GSM1367796,GSM1367797,GSM1367798,GSM1367799,GSM1367800,GSM1367801,GSM1367802,GSM1367803,GSM1367804,GSM1367805,GSM1367806,GSM1367807,GSM1367808,GSM1367809,GSM1367810,GSM1367811,GSM1367812,GSM1367813,GSM1367814,GSM1367815,GSM1367816,GSM1367817,GSM1367818,GSM1367819,GSM1367820,GSM1367821,GSM1367822,GSM1367823,GSM1367824,GSM1367825,GSM1367826,GSM1367827,GSM1367828,GSM1367829,GSM1367830,GSM1367831,GSM1367832,GSM1367833,GSM1367834,GSM1367835,GSM1367836,GSM1367837,GSM1367838,GSM1367839,GSM1367840,GSM1367841,GSM1367842,GSM1367843,GSM1367844,GSM1367845,GSM1367846,GSM1367847,GSM1367848,GSM1367849,GSM1367850,GSM1367851,GSM1367852,GSM1367853,GSM1367854,GSM1367855,GSM1367856,GSM1367857,GSM1367858,GSM1367859,GSM1367860,GSM1367861,GSM1367862,GSM1367863,GSM1367864,GSM1367865,GSM1367866,GSM1367867,GSM1367868,GSM1367869,GSM1367870,GSM1367871,GSM1367872,GSM1367873,GSM1367874,GSM1367875,GSM1367876,GSM1367877,GSM1367878,GSM1367879,GSM1367880,GSM1367881,GSM1367882,GSM1367883,GSM1367884,GSM1367885,GSM1367886,GSM1367887,GSM1367888,GSM1367889,GSM1367890,GSM1367891,GSM1367892,GSM1367893,GSM1367894,GSM1367895,GSM1367896,GSM1367897,GSM1367898,GSM1367899,GSM1367900,GSM1367901,GSM1453468,GSM1453471,GSM1453473,GSM1453475,GSM1453478,GSM1453480,GSM1453482,GSM1453485,GSM1525785,GSM1525786,GSM1525787,GSM1525788,GSM1525789,GSM1375434,GSM1375435,GSM1375436,GSM1375437,GSM1375438,GSM1375439,GSM1375440,GSM1375441,GSM1375442,GSM1375443,GSM1375444,GSM1375445,GSM1375446,GSM1375447,GSM1375448,GSM1375449,GSM1375450,GSM1375451,GSM1375452,GSM1375453,GSM1375454,GSM1375455,GSM1375456,GSM1375457,GSM1375458,GSM1375459,GSM1375460,GSM1375461,GSM1375462,GSM1375463,GSM1375464,GSM1375465,GSM1375466,GSM1375467,GSM1375468,GSM1375469,GSM1375470,GSM1375471,GSM1375472,GSM1381439,GSM1381440,GSM1381441,GSM1381442,GSM1385404,GSM1385405,GSM1385406,GSM1385407,GSM1385408,GSM1385409,GSM1385410,GSM1385411,GSM1385412,GSM1385413,GSM1385414,GSM1385415,GSM1399211,GSM1399212,GSM1399213,GSM1399214,GSM1399215,GSM1399216,GSM1399217,GSM1399218,GSM1399219,GSM1399220,GSM1417147,GSM1417148,GSM1417149,GSM1423259,GSM1423260,GSM1423262,GSM1423263,GSM1423265,GSM1423266,GSM1424870,GSM1424871,GSM1424872,GSM1424873,GSM1424874,GSM1424875,GSM1424876,GSM1424877,GSM1424878,GSM1424879,GSM1424880,GSM1440963,GSM1440964,GSM1440965,GSM1440966,GSM1440967,GSM1440968,GSM1456414,GSM1456415,GSM1456416,GSM1456417,GSM1456418,GSM1456419,GSM1456420,GSM1456421,GSM1456430,GSM1456431,GSM1456432,GSM1456433,GSM1456434,GSM1456435,GSM1456436,GSM1501578,GSM1462580,GSM1462581,GSM1462582,GSM1462583,GSM1466731,GSM1466732,GSM1466733,GSM1466734,GSM1466735,GSM1466736,GSM1466737,GSM1466738,GSM1481815,GSM1481816,GSM1481817,GSM1481818,GSM1487097,GSM1487098,GSM1487099,GSM1487100,GSM1487101,GSM1487102,GSM1487103,GSM1487104,GSM1487105,GSM1487106,GSM1487107,GSM1487108,GSM1487109,GSM1487110,GSM1487111,GSM1487112,GSM1498951,GSM1498952,GSM1498953,GSM1498954,GSM1498955,GSM1498956,GSM1498968,GSM1498969,GSM1498970,GSM1498971,GSM1498972,GSM1498973,GSM1498974,GSM1498975,GSM1515543,GSM1515544,GSM1515545,GSM1515546,GSM1515547,GSM1515548,GSM1515549,GSM1515550,GSM1526476,GSM1526477,GSM1532989,GSM1532990,GSM1532991,GSM1532992,GSM1532993,GSM1532994,GSM1532995,GSM1532996,GSM1532997,GSM1532998,GSM1532999,GSM1533000,GSM1545499,GSM1545500,GSM1545501,GSM1545502,GSM1545503,GSM1545504,GSM1545505,GSM1545506,GSM1545507,GSM1545508,GSM1545509,GSM1545510,GSM1545511,GSM1545512,GSM1545513,GSM1545514,GSM1545515,GSM1545516,GSM1545517,GSM1545518,GSM1545519,GSM1545520,GSM1545521,GSM1545522,GSM1545523,GSM1545524,GSM1545525,GSM1545526,GSM1545527,GSM1545528,GSM1545529,GSM1545530,GSM1545531,GSM1545532,GSM1545533,GSM1545534,GSM1571326,GSM1571327,GSM1571328,GSM1571329,GSM1525865,GSM1525866,GSM1525867,GSM1525868,GSM1525869,GSM1525870,GSM1525871,GSM1525872,GSM1525873,GSM1525874,GSM1525875,GSM1525876,GSM1525877,GSM1525878,GSM1525879,GSM1525880,GSM1525881,GSM1525882,GSM1525883,GSM1525884,GSM1525885,GSM1525886,GSM1525887,GSM1525888,GSM1525889,GSM1525890,GSM1525891,GSM1525892,GSM1525893,GSM1525894,GSM1525895,GSM1525896,GSM1525897,GSM1525898,GSM1525899,GSM1525900,GSM1525901,GSM1525902,GSM1525903,GSM1525904,GSM1525905,GSM1525906,GSM1525907,GSM1525908,GSM1525909,GSM1525910,GSM1525911,GSM1525912,GSM1525913,GSM1525914,GSM1569017,GSM1569018,GSM1569019,GSM1569020,GSM1569021,GSM1569022,GSM1569023,GSM1569024,GSM1569025,GSM1569026,GSM1569027,GSM1569028,GSM1569029,GSM1569030,GSM1581146,GSM1581147,GSM1581148,GSM1581149,GSM1581153,GSM1581154,GSM1581155,GSM1581156,GSM1582863,GSM1582864,GSM1582865,GSM1582866,GSM1582867,GSM1582868,GSM1582869,GSM1582870,GSM1582871,GSM1582872,GSM1582873,GSM1582874,GSM1584769,GSM1584770,GSM1584771,GSM1584772,GSM1584773,GSM1584774,GSM1584775,GSM1584776,GSM1584777,GSM1584778,GSM1584779,GSM1584780,GSM1584781,GSM1584782,GSM1584783,GSM1584784,GSM1585905,GSM1585906,GSM1585907,GSM1585908,GSM1585909,GSM1585910,GSM1585911,GSM1585912,GSM1585913,GSM1585914,GSM1585915,GSM1604049,GSM1604050,GSM1604051,GSM1604052,GSM1604053,GSM1604054,GSM1606370,GSM1606371,GSM1606372,GSM1606373,GSM1606374,GSM1606375,GSM1616876,GSM1616877,GSM1616878,GSM1616879,GSM1616880,GSM1616881,GSM1616882,GSM1616883,GSM1616884,GSM1616885,GSM1616886,GSM1616887,GSM1625043,GSM1625044,GSM1625045,GSM1625046,GSM1625047,GSM1625048,GSM1625049,GSM1625050,GSM1625051,GSM1625052,GSM1625053,GSM1625054,GSM1627067,GSM1627068,GSM1627069,GSM1627070,GSM1627071,GSM1627

## Stratify Balanced Training and Testing Sets in TARGET Gene Expression

Output training and testing gene expression datasets

In [19]:
#strat = pheno_df.set_index('sample_id').reindex(expr_df.index).primary_disease_code

In [20]:
# cancertype_count_df = (
#     pd.DataFrame(strat.value_counts()) #not using value_counts, what number should we use here? 
#     .reset_index()
#     .rename({'index': 'cancertype', 'primary_disease_code': 'n ='}, axis='columns')
# )

# file = os.path.join('data', 'target_sample_counts.tsv') #change which file - do we have a file that works for this?
# cancertype_count_df.to_csv(file, sep='\t', index=False)

# cancertype_count_df

In [21]:
train_df, test_df = train_test_split(expr_df,
                                     test_size=0.1,
                                     random_state=123) #if no stratify defined, should just randomize on its own

In [22]:
print(train_df.shape)
test_df.shape

(16353, 3756)

(1818, 3756)

In [23]:
#save train dataframe to file 
train_file = os.path.join('data', 'train_grein_rat_expression_matrix_processed.tsv.gz')
train_df.to_csv(train_file, sep='\t', compression='gzip', float_format='%.3g')

In [24]:
#save test dataframe to file 
test_file = os.path.join('data', 'test_grein_rat_expression_matrix_processed.tsv.gz')
test_df.to_csv(test_file, sep='\t', compression='gzip', float_format='%.3g')

## Sort genes based on median absolute deviation and output to file

In [25]:
# function to calculate median absolute deviation
def mad(df): 
    """Function to calculate median absolute deviation for a dataframe
  argument1 (dataframe): Dataframe for which to calculate the median absolute deviation, row by row

  Returns: The median absolute deviation for each row of the data frame
  """
    row_medians = df.median(axis='columns', numeric_only=True)
    abs_row_median_diffs = abs(df.sub(row_medians, axis='rows'))
    return abs_row_median_diffs.median(axis='columns', numeric_only=True)

In [26]:
# add gene_id as a column in dataframe
train_df['gene_id'] = train_df['gene'] + train_df['gene_symbol']
col = train_df.pop('gene_id')
train_df.insert(0, col.name, col)

train_df.head()

                                  gene_id                gene   gene_symbol  \
sample_id
3584             ENSRNOG00000007336Churc1  ENSRNOG00000007336        Churc1
14684            ENSRNOG00000035610Mir377  ENSRNOG00000035610        Mir377
17130      ENSRNOG00000048445LOC100909862  ENSRNOG00000048445  LOC100909862
66             ENSRNOG00000000169Spata5l1  ENSRNOG00000000169      Spata5l1
17164           ENSRNOG00000048549Olr1240  ENSRNOG00000048549       Olr1240

           GSM2668015  GSM2668016  GSM2668017  GSM2668018  GSM2668019  \
sample_id
3584         322.7576    237.0001    250.0003    186.1641    221.0005
14684         14.0000      7.0000      5.0000      8.0000      7.0000
17130          8.4862     11.3334      8.6440      9.1396      8.1458
66           225.5967    150.5534    161.6999    129.2117    132.6296
17164         31.3617     16.1621     14.9487     12.3349     11.9975

           GSM2668020  GSM2668021  GSM2668022  GSM2674552  GSM2674553  \
sample_id
3584         317.0003    250.6698    235.0003    126.0941    235.1763
14684          6.0000      9.0000      3.0000      0.0000      0.0000
17130         14.6378     13.0723      6.8770      0.0000      0.0000
66           188.6234    143.0324    132.2708    116.8599    102.3285
17164         22.6926     24.3146     15.8916      0.0000      0.0000

           GSM2674554  GSM2674555  GSM2674556  GSM2674557  GSM2674558  \
sample_id
3584         355.2647    479.3631    488.3686    465.3487    473.3577
14684          0.0000      0.0000      0.0000      0.0000      0.0000
17130          0.0000      0.0000      0.0000      0.0000      0.0000
66           195.1699    179.9838    169.8034    161.4641    175.8895
17164          0.0000      0.0000      0.0000      0.0000      0.0000

           GSM2674559  GSM2674560  GSM2674561  GSM2674562  GSM2674563  \
sample_id
3584         378.5225    187.7590    185.1417    451.4255    441.3341
14684          0.0000      0.0000      0.0000      0.0000      0.0000
17130          0.0000      0.0000      0.0000      0.0000      0.0000
66           186.4348     78.1931     88.6635    108.4148    124.4535
17164          0.0000      0.0000      0.0000      0.0000      0.0000

           GSM2674564  GSM2674565  GSM2674566  GSM2674567  GSM2683306  \
sample_id
3584         393.5051    326.2483    336.5778    414.4717   1801.3628
14684          0.0000      0.0000      0.0000      0.0000      2.9989
17130          0.0000      0.0000      0.0000      0.0000     13.7399
66           131.3203     98.6024    117.3997    129.5221    405.9823
17164          0.0000      0.0000      0.0000      0.0000     19.7699

           GSM2683307  GSM2683308  GSM2683309  GSM2683310  GSM2683311  \
sample_id
3584        1435.1920   1473.0381   1613.7095   1278.1563   1707.6946
14684          0.0000      0.0000      0.0000      2.0002      5.9990
17130          4.4305     11.3453      0.0081      7.7333      7.0126
66           348.4350    245.8922    376.0369    228.2067    371.6765
17164         12.4066     13.0108     20.8329     10.6476     20.3194

           GSM2683312  GSM2699989  GSM2699990  GSM2699991  GSM2699992  \
sample_id
3584        1893.1650    421.6607    433.8507    624.0168    656.0352
14684          2.0002      0.0000      0.0000      0.0000      0.0000
17130          8.2752      0.0000      0.0000      0.0000      0.0000
66           287.5426    153.5827    198.6694    239.0798    421.1322
17164         18.4805      0.0000      0.0000      0.0000      0.0000

           GSM2699993  GSM2699994  GSM2715971  GSM2715972  GSM2715973  \
sample_id
3584         693.1579    555.9830    338.5466    608.3494    461.2332
14684          0.0000      0.0000     20.2771     16.0929     15.2276
17130          0.0000      0.0000      0.0000      0.0000      0.0000
66           405.5692    353.1912    218.3926    270.6699    243.9780
17164          0.0000      0.0000      0.0000      0.0000      0.0000

           GSM2715974  GSM2715975  GSM2715976  GSM2715977  GSM2715978  \
sample_id
3584         421.2436    335.6425    359.3734    468.4659    354.2864
14684         16.7571     15.5750     30.0713     13.3653     11.5234
17130          0.0000      0.0000      0.0000      0.0000      0.0000
66           259.5685    187.4985    224.7382    290.8173    194.2398
17164          0.0000      0.0000      0.0000      0.0000      0.0000

           GSM2715979  GSM2715980  GSM2715981  GSM2715982  GSM2715983  \
sample_id
3584         424.7736    618.3934    530.0924    411.5948    134.8840
14684         24.4655     20.7144     25.5296     25.3654      4.9681
17130          0.0000      0.0000      0.0000      0.0000      0.0000
66           211.1198    274.8457    255.4217    244.9837     64.4822
17164          0.0000      0.0000      0.0000      0.0000      0.0000

           GSM2715984  GSM2715985  GSM2715986  GSM2715987  GSM2715988  \
sample_id
3584          66.2280    155.1942    121.0318    117.9883     75.4219
14684          5.8321      5.9796      5.1081      6.0609      3.0204
17130          0.0000      0.0000      0.0000      0.0000      0.0000
66            39.9238     52.8541     83.9811     65.2983     33.2502
17164          0.0000      0.0000      0.0000      0.0000      0.0000

           GSM2715989  GSM2715990  GSM2715991  GSM2715992  GSM2715993  \
sample_id
3584         110.5303    125.0355    265.9630     81.0537    271.4566
14684          2.0253      3.9835      5.8736      3.9679      0.9994
17130          0.0000      0.0000      0.0000      0.0000      0.0000
66            71.8474     60.4662    149.9750     60.6608    142.8185
17164          0.0000      0.0000      0.0000      0.0000      0.0000

           GSM2715994  GSM2715995  GSM2715996  GSM2715997  GSM2715998  \
sample_id
3584          94.7349    135.9667     74.0817    115.5591     59.4367
14684          3.9203      8.8134      0.0000      3.9543      3.0090
17130          0.0000      0.0000      0.0000      0.0000      0.0000
66            61.7248     92.5197     29.7591     93.5850     43.1000
17164          0.0000      0.0000      0.0000      0.0000      0.0000

           GSM2715999  GSM2716000  GSM2716001  GSM2716002  GSM2716003  \
sample_id
3584         164.1460    135.2351    152.2548    148.2874    156.8622
14684          4.0151      7.0404      0.9942      3.9622      4.9330
17130          0.0000      0.0000      0.0000      0.0000      0.0000
66            95.0483     99.0639    102.6225     85.4808     77.4664
17164          0.0000      0.0000      0.0000      0.0000      0.0000

           GSM2716004  GSM2716005  GSM2716006  GSM2716007  GSM2716008  \
sample_id
3584         113.0112    106.0951     87.6716    149.5794    131.0127
14684          8.1305     12.2005      7.1088      1.9639      7.6624
17130          0.0000      0.0000      0.0000      0.0000      0.0000
66            66.7587     93.2228     63.9363     73.5909     62.3487
17164          0.0000      0.0000      0.0000      0.0000      0.0000

           GSM2716009  GSM2716010  GSM2716011  GSM2716012  GSM2716013  \
sample_id
3584         109.8121    104.4139    130.4375    105.4170    130.1706
14684          7.9960      6.0308      7.1262      5.0575      6.9373
17130          0.0000      0.0000      0.0000      0.0000      0.0000
66            71.7533    105.9142     69.0887     79.1299    110.7773
17164          0.0000      0.0000      0.0000      0.0000      0.0000

           GSM2716014  GSM2716015  GSM2716016  GSM2716017  GSM2716018  \
sample_id
3584         109.6182    108.9170     97.9336     81.8168     89.4099
14684          4.0132      3.8868      8.0015      7.0525      6.9728
17130          0.0000      0.0000      0.0000      0.0000      0.0000
66            66.4696     74.0173     85.1677     62.4723     64.5120
17164          0.0000      0.0000      0.0000      0.0000      0.0000

           GSM2716019  GSM2716020  GSM2716021  GSM2716022  GSM2716023  \
sample_id
3584         129.5933    105.2990    104.0971    124.0989    100.5781
14684         11.5877      6.5975      7.9103      9.8487      1.9497
17130          0.0000      0.0000      0.0000      0.0000      0.0000
66            76.9956     53.2100     72.9371     99.9097     65.9237
17164          0.0000      0.0000      0.0000      0.0000      0.0000

           GSM2716024  GSM2716025  GSM2716026  GSM2716027  GSM2716028  \
sample_id
3584         150.4217    573.6396    394.4026    576.8550    439.6081
14684          6.8500     17.9302     18.0804     12.6321     19.8792
17130          0.0000      0.0000      0.0000      0.0000      0.0000
66            72.5521    345.2647    220.1329    338.7096    231.9264
17164          0.0000      0.0000      0.0000      0.0000      0.0000

           GSM2716029  GSM2716030  GSM2716031  GSM2716032  GSM2716033  \
sample_id
3584         321.6116    485.1893    354.9365    410.3097    635.4067
14684         27.6723     13.8692     14.0329     16.6629      6.8573
17130          0.0000      0.0000      0.0000      0.0000      0.0000
66           204.8120    285.3455    221.4877    226.2166    316.0313
17164          0.0000      0.0000      0.0000      0.0000      0.0000

           GSM2716034  GSM2716035  GSM2716036  GSM2716037  GSM2716038  \
sample_id
3584         206.5214     84.2760    112.7959    156.5970    102.6201
14684          9.0522      7.3114      6.2429     10.8525      6.0947
17130          0.0000      0.0000      0.0000      0.0000      0.0000
66           128.8402     44.8590     79.3851     99.5636     53.5822
17164          0.0000      0.0000      0.0000      0.0000      0.0000

           GSM2716039  GSM2716040  GSM2716041  GSM2716042  GSM2716043  \
sample_id
3584         101.5993     85.6848     88.3153     71.9229     89.0246
14684          4.1534      0.0000      4.8465      4.8269      2.0350
17130          0.0000      0.0000      0.0000      0.0000      0.0000
66            77.5646     71.0719     75.4628     69.1277     45.3972
17164          0.0000      0.0000      0.0000      0.0000      0.0000

           GSM2716044  GSM2716045  GSM2716046  GSM2716047  GSM2716048  \
sample_id
3584          94.5550    100.7506    125.4631     90.9257    153.7800
14684         12.2618      8.1333      0.0000      5.9863      2.9769
17130          0.0000      0.0000      0.0000      0.0000      0.0000
66            73.8295     66.0270     47.0629     67.4894    122.4353
17164          0.0000      0.0000      0.0000      0.0000      0.0000

           GSM2716049  GSM2716050  GSM2716051  GSM2716052  GSM2716053  \
sample_id
3584          76.8803     89.7153     41.4257    104.0952     53.9264
14684          2.0293      4.0979      1.0168      4.8031      8.8072
17130          0.0000      0.0000      0.0000      0.0000      0.0000
66            62.4171     58.9993     32.8092     76.8147     60.7903
17164          0.0000      0.0000      0.0000      0.0000      0.0000

           GSM2716054  GSM2716055  GSM2716056  GSM2716057  GSM2716058  \
sample_id
3584         110.5566    107.6762     88.6346     90.5086    122.0237
14684          9.6695      0.0000      6.0292      4.9371      5.9122
17130          0.0000      0.0000      0.0000      0.0000      0.0000
66            78.7147     61.3414     55.4903     83.3017     82.4234
17164          0.0000      0.0000      0.0000      0.0000      0.0000

           GSM2716059  GSM2716060  GSM2716061  GSM2716062  GSM2716063  \
sample_id
3584          14.6683    127.2837    107.1669    110.7847    113.5956
14684          1.0007      5.0591      7.1213      3.0110      5.0050
17130          0.0000      0.0000      0.0000      0.0000      0.0000
66            34.3715     86.0824     62.6142     78.2495     69.2679
17164          0.0000      0.0000      0.0000      0.0000      0.0000

           GSM2716064  GSM2716065  GSM2716066  GSM2716067  GSM2716068  \
sample_id
3584          73.7633     92.4169    105.2344     90.9446     80.5649
14684          5.1571      7.2254      6.1497      2.0492      7.3593
17130          0.0000      0.0000      0.0000      0.0000      0.0000
66            74.6263     72.2719     58.4166     73.7528     67.5663
17164          0.0000      0.0000      0.0000      0.0000      0.0000

           GSM2716069  GSM2716070  GSM2716071  GSM2716072  GSM2750963  \
sample_id
3584         128.7207    121.5221    109.4078    118.8756    626.3472
14684          5.2775      3.8185      9.6841      6.6567      0.0000
17130          0.0000      0.0000      0.0000      0.0000      0.0000
66            84.9609     77.1686     78.1659     75.2933    218.2589
17164          0.0000      0.0000      0.0000      0.0000      0.0000

           GSM2750964  GSM2750965  GSM2750966  GSM2750967  GSM2750968  \
sample_id
3584         686.3591    864.3908    778.7125    938.6924    920.6573
14684          0.0000      0.0000      0.0000      0.0000      0.0000
17130          0.0000      0.0000      0.0000      0.0000      0.0000
66           210.0358    189.5344    241.0669    159.4389    173.7321
17164          0.0000      0.0000      0.0000      0.0000      0.0000

           GSM2752505  GSM2752506  GSM2778522  GSM2778523  GSM2778524  \
sample_id
3584        2623.2380   2886.1756    325.0693    230.7509     94.8999
14684          0.0000      0.0000      0.0000      0.0000      0.0000
17130          0.0000      0.0000      0.0000      0.0000      0.0000
66           353.2094    295.2845     52.2987     31.3840      0.0000
17164          0.0000      1.1682      0.0000      0.0000      0.0000

           GSM2778525  GSM2778526  GSM2778527  GSM2778528  GSM2778529  \
sample_id
3584           0.0000    109.2008       0.000         0.0         0.0
14684          0.0000      0.0000       0.000         0.0         0.0
17130          0.0000      0.0000       0.000         0.0         0.0
66             1.0205      1.0286      10.201         0.0         0.0
17164          0.0000      0.0000       0.000         0.0         0.0

           GSM2778530  GSM2778531  GSM2778532  GSM2778533  GSM2778534  \
sample_id
3584          29.3482         0.0         0.0         0.0    152.6092
14684          0.0000         0.0         0.0         0.0      0.0000
17130          0.0000         0.0         0.0         0.0      0.0000
66             0.0000         0.0         0.0         0.0      0.0000
17164          0.0000         0.0         0.0         0.0      0.0000

           GSM2778535  GSM2778536  GSM2778537  GSM2778538  GSM2778539  \
sample_id
3584           0.0000         0.0         0.0      0.0000    163.3581
14684          0.0000         0.0         0.0      0.0000      0.0000
17130          0.0000         0.0         0.0      0.0000      0.0000
66             2.1563         0.0         0.0     25.9811     57.0601
17164          0.0000         0.0         0.0      0.0000      0.0000

           GSM2778540  GSM2778541  GSM2778542  GSM2778543  GSM2778544  \
sample_id
3584            0.000     46.7494    323.0271    374.6256     56.7867
14684           0.000      0.0000      0.0000      0.0000      0.0000
17130           0.000      0.0000      0.0000      0.0000      0.0000
66              4.954      0.0000     18.9637      1.0028      2.0478
17164           0.000      0.0000      0.0000      0.0000      0.0000

           GSM2778545  GSM2778546  GSM2778547  GSM2778548  GSM2778549  \
sample_id
3584         267.0934         0.0      0.0000    176.2518         0.0
14684          0.0000         0.0      0.0000      0.0000         0.0
17130          0.0000         0.0      0.0000      0.0000         0.0
66             0.0000         0.0      3.6206     54.5286         0.0
17164          0.0000         0.0      0.0000      0.0000         0.0

           GSM2778550  GSM2778551  GSM2778552  GSM2778553  GSM2778554  \
sample_id
3584           6.4181      3.0904     73.3722         0.0    467.0744
14684          0.0000      0.0000      0.0000         0.0      0.0000
17130          0.0000      0.0000      0.0000         0.0      0.0000
66             1.5080      5.2318      0.0000         0.0      0.0000
17164          0.0000      0.0000      0.0000         0.0      0.0000

           GSM2778555  GSM2778556  GSM2778557  GSM2778558  GSM2778559  \
sample_id
3584              0.0      0.0000      0.0000         0.0    537.8799
14684             0.0      0.0000      0.0000         0.0      0.0000
17130             0.0      0.0000      0.0000         0.0      0.0000
66                0.0      5.0353      3.0039         0.0      1.0141
17164             0.0      0.0000      0.0000         0.0      0.0000

           GSM2778560  GSM2778561  GSM2778562  GSM2778563  GSM2778564  \
sample_id
3584          44.6411      1.0949         0.0     44.3417     66.2251
14684          0.0000      0.0000         0.0      0.0000      0.0000
17130          0.0000      0.0000         0.0      0.0000      0.0000
66             2.9327      6.0057         0.0      0.0000     11.7542
17164          0.0000      0.0000         0.0      0.0000      0.0000

           GSM2778565  GSM2778566  GSM2778567  GSM2778568  GSM2778569  \
sample_id
3584              0.0     87.6742         0.0         0.0     13.3386
14684             0.0      0.0000         0.0         0.0      0.0000
17130             0.0      0.0000         0.0         0.0      0.0000
66                0.0      0.0000         0.0         0.0      0.9938
17164             0.0      0.0000         0.0         0.0      0.0000

           GSM2778570  GSM2778571  GSM2778572  GSM2778573  GSM2778574  \
sample_id
3584              0.0       0.000    100.1211     34.9399     68.8784
14684             0.0       0.000      0.0000      0.0000      0.0000
17130             0.0       0.000      0.0000      0.0000      0.0000
66                0.0      14.215      0.0000     15.2858      0.0000
17164             0.0       0.000      0.0000      0.0000      0.0000

           GSM2778575  GSM2778576  GSM2778577  GSM2778578  GSM2778579  \
sample_id
3584              0.0         0.0         0.0     21.2891         0.0
14684             0.0         0.0         0.0      0.0000         0.0
17130             0.0         0.0         0.0      0.0000         0.0
66                0.0         0.0         0.0      1.0363         0.0
17164             0.0         0.0         0.0      0.0000         0.0

           GSM2778580  GSM2778581  GSM2778582  GSM2778583  GSM2778584  \
sample_id
3584          30.5609    128.8438    163.8683      0.8867      1.7924
14684          0.0000      0.0000      0.0000      0.0000      0.0000
17130          0.0000      0.0000      0.0000      0.0000      0.0000
66             4.6713     19.0638      0.0000      1.1615      1.0425
17164          0.0000      0.0000      0.0000      0.0000      0.0000

           GSM2778585  GSM2778586  GSM2778587  GSM2778588  GSM2778589  \
sample_id
3584         110.1458      0.0000     16.2116    167.3828      0.9693
14684          0.0000      0.0000      0.0000      0.0000      0.0000
17130          0.0000      0.0000      0.0000      0.0000      0.0000
66             0.0000      4.3146      7.9782      1.0091      0.0000
17164          0.0000      0.0000      0.0000      0.0000      0.0000

           GSM2778590  GSM2778591  GSM2778592  GSM2778593  GSM2778594  \
sample_id
3584         136.4178    164.3362     29.4326         0.0         0.0
14684          0.0000      0.0000      0.0000         0.0         0.0
17130          0.0000      0.0000      0.0000         0.0         0.0
66             0.0000      1.3135      2.4984         0.0         0.0
17164          0.0000      0.0000      0.0000         0.0         0.0

           GSM2778595  GSM2778596  GSM2778597  GSM2778598  GSM2778599  \
sample_id
3584           0.0000      0.0000         0.0     36.1077     98.9872
14684          0.0000      0.0000         0.0      0.0000      0.0000
17130          0.0000      0.0000         0.0      0.0000      0.0000
66             6.1209      2.6741         0.0      0.0000      1.0468
17164          0.0000      0.0000         0.0      0.0000      0.0000


In [27]:
# Determine most variably expressed genes and subset
# create dataframe to save median absolute deviation data for rats
train_df_mad = mad(train_df.drop(['gene_id','gene', 'gene_symbol'], axis = 1))
train_df_mad.columns = ['gene_id', 'median_abs_deviation']

train_df_mad = train_df_mad.sort_values(ascending=False)
train_df_mad

sample_id
14526    209003.09560
13670     83535.22635
13990     82757.71810
13940     68116.18140
13586     60134.21585
             ...
4073          0.00000
17793         0.00000
11552         0.00000
12362         0.00000
5673          0.00000
Length: 16353, dtype: float64

In [28]:
# Save to tsv file
file = os.path.join('data', 'grein_mad_rat_genes.tsv')
train_df_mad.to_csv(file, sep='\t', index=False)